[versions]
agp = "8.8.0"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.04.01"
navigationComposeJvmstubs = "2.9.5"
ksp = "2.0.21-1.0.25"           # NUEVO EN VERSIONS
room = "2.6.1"                  # NUEVO EN VERSIONS *
roomCommonJvm = "2.8.1"         # NUEVO EN VERSIONS *
roomKtx = "2.8.1"               # NUEVO EN VERSIONS
lifecycle = "2.8.6"             # NUEVO EN VERSIONS

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose-jvmstubs = { group = "androidx.navigation", name = "navigation-compose-jvmstubs", version.ref = "navigationComposeJvmstubs" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }         # NUEVO EN LIBRARIES
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }                 # NUEVO EN LIBRARIES
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }       # NUEVO EN LIBRARIES
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }           # NUEVO EN LIBRARIES
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" } # NUEVO EN LIBRARIES


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }           # NUEVO EN PLUGINS
